package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type DesktopEntry struct {
	Path       string
	Name       string
	Exec       string
	Icon       string
	Version    string
	Categories string
}

func CreateDesktopEntryAtomic(config *Config, name, execCmd, iconPath, version, categories string) (string, error) {
	safeName := strings.ReplaceAll(filepath.Base(name), " ", "_")
	desktopFile := safeName + ".desktop"
	desktopPath := filepath.Join(config.UpdateDir, desktopFile)
	tempPath := desktopPath + ".tmp"

	content := fmt.Sprintf(`[Desktop Entry]
Name=%s
Exec=%s
Icon=%s
Type=Application
Version=%s
Categories=%s
Comment=Generated by AppImageXdg
`, name, execCmd, iconPath, version, categories)

	if err := os.WriteFile(tempPath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("write temp desktop file: %w", err)
	}

	if err := os.Rename(tempPath, desktopPath); err != nil {
		os.Remove(tempPath)
		return "", fmt.Errorf("rename temp to final: %w", err)
	}

	exec.Command("update-desktop-database", config.UpdateDir).Run()

	return desktopPath, nil
}

func UpdateDesktopFileExec(desktopPath, oldExec, newExec string) error {
	data, err := os.ReadFile(desktopPath)
	if err != nil {
		return err
	}
	content := strings.ReplaceAll(string(data), oldExec, newExec)
	return os.WriteFile(desktopPath, []byte(content), 0644)
}

func ListAppImageDesktopEntries(updateDir string) ([]DesktopEntry, error) {
	var entries []DesktopEntry

	matches, err := filepath.Glob(filepath.Join(updateDir, "*.desktop"))
	if err != nil {
		return nil, err
	}

	for _, path := range matches {
		entry := parseDesktopEntry(path)
		if entry != nil && strings.Contains(strings.ToLower(entry.Exec), ".appimage") {
			entries = append(entries, *entry)
		}
	}
	return entries, nil
}

func parseDesktopEntry(path string) *DesktopEntry {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()

	entry := &DesktopEntry{Path: path}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		switch {
		case strings.HasPrefix(line, "Name="):
			entry.Name = strings.TrimPrefix(line, "Name=")
		case strings.HasPrefix(line, "Exec="):
			entry.Exec = strings.TrimPrefix(line, "Exec=")
		case strings.HasPrefix(line, "Icon="):
			entry.Icon = strings.TrimPrefix(line, "Icon=")
		case strings.HasPrefix(line, "Version="):
			entry.Version = strings.TrimPrefix(line, "Version=")
		case strings.HasPrefix(line, "Categories="):
			entry.Categories = strings.TrimPrefix(line, "Categories=")
		}
	}
	return entry
}

func DesktopFileExists(updateDir, appImageName string) bool {
	entries, _ := ListAppImageDesktopEntries(updateDir)
	baseName := strings.TrimSuffix(appImageName, filepath.Ext(appImageName))

	for _, e := range entries {
		if strings.Contains(strings.ToLower(e.Exec), strings.ToLower(baseName)) {
			return true
		}
	}
	return false
}

func FindDesktopEntries(updateDir, searchTerm string) []DesktopEntry {
	entries, _ := ListAppImageDesktopEntries(updateDir)
	term := strings.ToLower(searchTerm)

	var matches []DesktopEntry
	for _, e := range entries {
		nameLower := strings.ToLower(e.Name)
		baseName := strings.ToLower(strings.TrimSuffix(filepath.Base(e.Path), ".desktop"))

		if strings.Contains(nameLower, term) ||
			nameLower == term ||
			strings.Contains(baseName, term) {
			matches = append(matches, e)
		}
	}
	return matches
}

func RemoveDesktopEntry(config *Config, entry DesktopEntry) error {
	if entry.Icon != "" &&
		(strings.Contains(entry.Icon, "AppImageXdg") ||
			strings.Contains(entry.Icon, "/icons/")) {
		os.Remove(entry.Icon)
	}

	if err := os.Remove(entry.Path); err != nil {
		return err
	}

	exec.Command("update-desktop-database", config.UpdateDir).Run()
	return nil
}

func ExecLineToPath(execLine string) string {
	path := strings.Trim(execLine, "\"")
	path = strings.TrimSuffix(path, " --no-sandbox")
	return path
}
